const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const here = __dirname;
const template = fs.readFileSync(path.join(here, 'app.template.html'), 'utf8');
const model = fs.readFileSync(path.join(here, 'model.js'), 'utf8');
const index = fs.readFileSync(path.join(here, 'index.html'), 'utf8');

assert.equal(index, template.replace('/*__ION_FLIGHT_MODEL__*/', model), 'index.html must exactly match the checked-in source bundle');
assert.ok(index.includes(model), 'the tested production model must be embedded verbatim');
const scripts = index.split('<script>').slice(1).map(chunk => chunk.split('</script>')[0]);
assert.equal(scripts.length, 2, 'the bundle should contain model and app scripts');
scripts.forEach((script, number) => new Function(script));
assert.match(index, /Arrival values and the trace stay hidden until you run the detector/);
assert.match(index, /CORE_TRACE_DOMAIN_US/);
assert.match(index, /runToken/);
assert.match(index, /cancelAnimationFrame/);
assert.match(index, /peaks\.reduce\(\(total, peakData\)/, 'detector trace must sum packet signals');
assert.match(index, /const summedDensity = \(result, timeUs\)/, 'advanced traces must use summed detector signals');
assert.match(index, /Both rows use the same vertical signal scale/);
assert.match(index, /completed \|\| runtime\.phase === 'running'/, 'predictions must lock during a run');
assert.match(index, /scrollIntoView\(\{ behavior: 'instant'/, 'Run must reveal the instrument before timing begins');
assert.match(index, /@media \(max-width: 620px\)[\s\S]*\.instrument-head \{ align-items: flex-start; flex-direction: column; \}/);
assert.doesNotMatch(index, /mastered|M\.challenges/);
assert.match(index, /teacher-guide\.html/);
const check = spawnSync(process.execPath, ['build.js', '--check'], { cwd: here, encoding: 'utf8' });
assert.equal(check.status, 0, check.stderr || check.stdout);
assert.match(check.stdout, /read-only check/);
console.log('Ion Flight bundle: production modules, lesson gating, cancellation hooks, inline syntax, and read-only build check passed.');
