#!/usr/bin/env node
// build-hub.js — regenerates the README demo table and the launcher card bodies
// from the per-demo demo.json manifests, validates declared files, and prints a
// compliance report against CONTRACT.md.
//
// Usage:
//   node tools/build-hub.js           regenerate README.md + index.html cards
//   node tools/build-hub.js --check   report drift without writing (exit 1 on drift)
//
// Ownership boundaries: this script owns the README table between the
// demo-table markers and the INNER content of every <a class="card"> block in
// index.html. Section headings, narrative prose, and card order stay
// hand-authored in index.html; tours/*.json defines README table order.
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CHECK = process.argv.includes('--check');
let failed = false;
function fail(msg) { console.error('ERROR: ' + msg); failed = true; }

// ---- collect manifests -----------------------------------------------------
const demos = {};
for (const ent of fs.readdirSync(ROOT, { withFileTypes: true })) {
  if (!ent.isDirectory()) continue;
  const mPath = path.join(ROOT, ent.name, 'demo.json');
  if (!fs.existsSync(mPath)) continue;
  let m;
  try { m = JSON.parse(fs.readFileSync(mPath, 'utf8')); }
  catch (e) { fail(`${ent.name}/demo.json is not valid JSON: ${e.message}`); continue; }
  if (m.slug !== ent.name) fail(`${ent.name}/demo.json slug "${m.slug}" does not match its folder name`);
  demos[ent.name] = m;
}
if (!Object.keys(demos).length) { fail('no demo.json manifests found'); process.exit(1); }

// ---- validate declared files ----------------------------------------------
for (const [slug, m] of Object.entries(demos)) {
  const need = [m.entry || 'index.html', 'README.md'];
  if (m.guide) need.push(m.guide.html, m.guide.pdf);
  for (const f of need.filter(Boolean)) {
    if (!fs.existsSync(path.join(ROOT, slug, f))) fail(`${slug}: declared file missing: ${f}`);
  }
}

// ---- ordering from tours ---------------------------------------------------
const tourDir = path.join(ROOT, 'tours');
const order = [];
if (fs.existsSync(tourDir)) {
  for (const f of fs.readdirSync(tourDir).filter(f => f.endsWith('.json')).sort()) {
    let tour;
    try { tour = JSON.parse(fs.readFileSync(path.join(tourDir, f), 'utf8')); }
    catch (e) { fail(`tours/${f} is not valid JSON: ${e.message}`); continue; }
    for (const sec of tour.sections || []) {
      for (const slug of sec.demos || []) {
        if (!demos[slug]) fail(`tours/${f}: unknown demo "${slug}"`);
        else if (!order.includes(slug)) order.push(slug);
      }
    }
  }
}
const untoured = Object.keys(demos).filter(s => !order.includes(s)).sort();
if (untoured.length) console.log('note: demos in no tour (appended alphabetically): ' + untoured.join(', '));
const ordered = order.concat(untoured);

// ---- README table ----------------------------------------------------------
const mdEscape = s => String(s).replace(/\|/g, '\\|');
const tableLines = ['| Demo | Description |', '|------|-------------|'];
for (const slug of ordered) {
  tableLines.push(`| [${slug}](${slug}/) | ${mdEscape(demos[slug].description)} |`);
}
const BEGIN = '<!-- demo-table:begin (generated by tools/build-hub.js — do not edit by hand) -->';
const END = '<!-- demo-table:end -->';
const readmePath = path.join(ROOT, 'README.md');
let readme = fs.readFileSync(readmePath, 'utf8');
const b = readme.indexOf(BEGIN), e = readme.indexOf(END);
if (b === -1 || e === -1 || e < b) {
  fail('README.md is missing the demo-table markers');
} else {
  const next = readme.slice(0, b + BEGIN.length) + '\n' + tableLines.join('\n') + '\n' + readme.slice(e);
  if (next !== readme) {
    if (CHECK) fail('README.md table is out of date (run node tools/build-hub.js)');
    else { fs.writeFileSync(readmePath, next); console.log('README.md: demo table regenerated'); }
  } else console.log('README.md: up to date');
}

// ---- launcher cards --------------------------------------------------------
const idxPath = path.join(ROOT, 'index.html');
let idx = fs.readFileSync(idxPath, 'utf8');
const carded = [];
const nextIdx = idx.replace(
  /([ \t]*)<a class="card" href="([a-z0-9-]+)\/index\.html">[\s\S]*?<\/a>/g,
  (whole, indent, slug) => {
    const m = demos[slug];
    if (!m) { fail(`index.html: card links unknown demo "${slug}"`); return whole; }
    carded.push(slug);
    return [
      `${indent}<a class="card" href="${slug}/index.html">`,
      `${indent}  <div class="topic">${m.topic}</div>`,
      `${indent}  <h2><span class="emoji">${m.emoji}</span>${m.title}</h2>`,
      `${indent}  <p>${m.card_blurb}</p>`,
      `${indent}  <div class="go">Open demo →</div>`,
      `${indent}</a>`,
    ].join('\n');
  }
);
for (const slug of ordered) {
  if (!carded.includes(slug)) console.log(`note: ${slug} has no launcher card (add a stub <a class="card" href="${slug}/index.html"></a> where it belongs)`);
}
if (nextIdx !== idx) {
  if (CHECK) fail('index.html cards are out of date (run node tools/build-hub.js)');
  else { fs.writeFileSync(idxPath, nextIdx); console.log('index.html: card bodies regenerated'); }
} else console.log('index.html: up to date');

// ---- compliance report -----------------------------------------------------
const keys = [...new Set(ordered.flatMap(s => Object.keys(demos[s].compliance || {})))];
const sym = v => v === true ? 'Y' : v === false ? 'X' : '?';
console.log('\ncompliance (Y yes / X no / ? unverified):');
const w = Math.max(...ordered.map(s => s.length)) + 2;
console.log(' '.repeat(w) + keys.map(k => k.slice(0, 14).padEnd(15)).join(''));
for (const slug of ordered) {
  const c = demos[slug].compliance || {};
  console.log(slug.padEnd(w) + keys.map(k => sym(c[k]).padEnd(15)).join(''));
}
const missingProv = ordered.filter(s => !(demos[s].built_with || []).length);
if (missingProv.length) console.log('\nnote: built_with provenance unrecorded for: ' + missingProv.join(', '));

process.exit(failed ? 1 : 0);
