'use strict';
const assert = require('node:assert/strict');
const M = require('./model.js');
const close = (actual, expected, message) => assert.ok(Math.abs(actual - expected) < 1e-9, message + ': expected ' + expected + ', got ' + actual);

close(M.baselineRate(0), 0, 'S=0 baseline');
close(M.baselineRate(M.KM), 50, 'baseline rate at Km');
close(M.rate(M.KM, 1, 1), M.baselineRate(M.KM), 'zero inhibition factors recover baseline');
assert.ok(M.predictedRate('competitive', 1e9) > 99.9999, 'competitive saturates near 100');
assert.ok(Math.abs(M.predictedRate('uncompetitive', 1e9) - 100 / 3) < 1e-6, 'uncompetitive saturates near 100/3');
assert.ok(Math.abs(M.predictedRate('pure-noncompetitive', 1e9) - 100 / 3) < 1e-6, 'pure noncompetitive saturates near 100/3');
close(M.predictedRate('competitive', 2), 25, 'competitive at Km');
close(M.predictedRate('uncompetitive', 2), 25, 'uncompetitive at Km');
close(M.predictedRate('pure-noncompetitive', 2), 100 / 6, 'pure noncompetitive at Km');
assert.ok(M.predictedRate('competitive', 20) > M.predictedRate('uncompetitive', 20), 'high substrate: competitive exceeds uncompetitive');
assert.ok(M.predictedRate('uncompetitive', 20) > M.predictedRate('pure-noncompetitive', 20), 'high substrate: uncompetitive exceeds pure noncompetitive');

let state = M.createCase(0);
assert.equal(M.createCase(1).hiddenId, 'uncompetitive', 'new sample sequence advances to a distinct finite case');
assert.equal(M.createCase(2).hiddenId, 'pure-noncompetitive', 'new sample sequence reaches the third finite case');
assert.equal(M.createCase(3).hiddenId, 'competitive', 'new sample sequence cycles without changing the model');
let run = M.runAssay(state, 2); state = run.state;
assert.equal(run.kind, 'recorded');
assert.deepEqual(M.compatibleHypotheses(state.assays).map(item => item.id), ['competitive', 'uncompetitive']);
assert.equal(M.evidenceStatus(state.assays).kind, 'ambiguous', 'Km-only observation is explicitly insufficient');
let pure = M.createCase(2);
pure = M.runAssay(pure, 2).state;
assert.deepEqual(M.compatibleHypotheses(pure.assays).map(item => item.id), ['pure-noncompetitive'], 'the visibly distinct 16.7 teaching-unit prediction identifies pure noncompetitive within the finite set');
run = M.runAssay(state, 20); state = run.state;
assert.deepEqual(M.compatibleHypotheses(state.assays).map(item => item.id), ['competitive']);
assert.equal(M.evidenceStatus(state.assays).kind, 'discriminated', 'high-substrate observation discriminates the finite candidates');
assert.equal(M.explanationIsSound(state.assays, 'isolates-pattern'), true);
assert.equal(M.explanationIsSound(state.assays, 'real-binding-site'), false, 'the model does not validate a real binding-site claim');
const duplicate = M.runAssay(state, 20);
assert.equal(duplicate.kind, 'duplicate'); assert.equal(duplicate.state.assays.length, 2, 'duplicate does not consume an assay');
let tight = M.createCase(1);
for (const s of [0, 1, 2, 20]) tight = M.runAssay(tight, s).state;
assert.equal(M.runAssay(tight, 8).kind, 'budget', 'four-assay budget is enforced');
assert.equal(M.transferFeedback(2).distinct, false, 'transfer control: Km repeats the ambiguity');
assert.equal(M.transferFeedback(2).eliminated, 0, 'transfer control eliminates no candidate');
assert.equal(M.transferFeedback(1).eliminated, 1, 'transfer: S=1 separates the tied candidates');
assert.equal(M.transferFeedback(8).eliminated, 1, 'transfer: S=8 separates the tied candidates');
assert.equal(M.transferFeedback(20).distinct, true, 'transfer: high substrate separates the remaining candidates');
assert.equal(M.transferFeedback(20).eliminated, 1, 'transfer: high substrate eliminates one candidate');
console.log('PASS  independent hand-calculated rate, ambiguity, discrimination, budget, duplicate, and transfer fixtures');
